# Generated by Django 2.1.7 on 2020-05-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base110', '0002_auto_20190221_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta1', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta2', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta3', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta4', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta5', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta6', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta7', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta8', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta9', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta10', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
