# Generated by Django 2.1.7 on 2020-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base110', '0004_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static/csv'),
        ),
    ]
